### ISSUE TITLE
Having issues with open_path

### ISSUE THREAD

**Issue by Manul-Keyboard** [ruabmbua/hidapi-rs#102]
Code:

```rust
use hidapi::HidApi;

fn main() {
    let r_id = 2;
    let msg = "test";
    let msg_bytes = msg.as_bytes();

    let api = HidApi::new().unwrap();

    const path: &str = "1-3:1.0";

    for dev in api.device_list() {
        let cstr_path = dev.path();
        let str_path: &str = cstr_path.to_str().unwrap();

        if str_path == path {
            let device = api.open_path(&cstr_path).unwrap();
            let mut package = vec![r_id];
            package.extend_from_slice(&msg_bytes);

            device.write(&package).unwrap();
        }
    }
}
```

Error:
![image](https://user-images.githubusercontent.com/109975829/218790439-013f1382-d346-4a3d-99ab-a31a1ae09114.png)
The error was produced on Linux.

**Comment by ruabmbua** [comment]
If you are trying to open a specific interface of a device in a portable way, maybe this is of interest: https://github.com/ruabmbua/hidapi-rs/issues/101

**Comment by ruabmbua** [comment]
Note that the *paths* are not portable at all across operating systems, and more of an implementation detail. They are mostly useful, if you somehow already have the path you want to use. The "1-3:1.0" might only be e.g. for windows.

Also I just noticed that the legacy libusb backend has paths like this, but hidapi uses hidraw as the default now.

**Comment by ruabmbua** [comment]
Also a small tip: when filing issues, please do not include code snippets as pictures, rather use the proper code comments, or just plain text. Its not super important but it makes life a bit more pleasant for people trying to reproduce issues, because they can just copy the text. Also, for search purposes text is much better.

**Comment by Manul-Keyboard** [comment]
Thank you for your answer. I will use code comments in the future.
