### ISSUE TITLE
Add `get_report_descriptor`

### ISSUE THREAD

**Issue by maniwani** [ruabmbua/hidapi-rs#104]
`hidapi` recently added HID report descriptor parsing in https://github.com/libusb/hidapi/pull/451 for the (upcoming?) 0.14.0 version. Can it be made accessible here?

**Comment by ruabmbua** [comment]
I am going to wait for the official update of the C library, but when it eventually releases I will add the new function.

**Comment by ruabmbua** [comment]
You can use the branch https://github.com/ruabmbua/hidapi-rs/tree/hid-report-descriptor for now as a direct cargo git dependency. Tested it on linux ans seems to work.

**Comment by maniwani** [comment]
Thanks!

**Comment by TheElectronWill** [comment]
[hidapi 0.14.0 has been released](https://github.com/libusb/hidapi/releases/tag/hidapi-0.14.0) :tada:

**Comment by ruabmbua** [comment]
I will look into updating and then rebasing the hid-report-descriptor branch onto master. Although it probably has to wait until end of next week when I have time again and can access my workstation for testing on all the different platforms.
