### ISSUE TITLE
public call to `close` missing

### ISSUE THREAD

**Issue by shufps** [ruabmbua/hidapi-rs#137]
libusb hidapi has a `close` function:

https://github.com/libusb/hidapi/blob/master/hidapi/hidapi.h#L481

This crate has a call to it via `ffi::hid_close(device)`

But the crate itself doesn't expose the close - is there a way how we could do it?

Problem is that we open a device multiple times what leads to errors after a couple of minutes and we would like to close it before opening it again.

**Comment by liugangnhm** [comment]
i have the same question

**Comment by ruabmbua** [comment]
If you want to close a device, you need to drop the `HidDevice`.
