### ISSUE TITLE
How to differentiate and connect to those devices which with same VID&PID?

### ISSUE THREAD

**Issue by Fred2754** [ruabmbua/hidapi-rs#142]
I did not how, there are lots of devices with repetition VID&PID but different name in the my win11.
![Snipaste_2024-01-14_21-05-49](https://github.com/ruabmbua/hidapi-rs/assets/156586699/93cb1bdd-de83-4c36-8fbb-0404f93cb001)

**Comment by ruabmbua** [comment]
This question was already asked multiple times. Guess I will need to add a QA section to the readme.

See here: https://github.com/ruabmbua/hidapi-rs/issues/89

**Comment by Fred2754** [comment]
Sorry guy, pls close this issue.
Little more example codes would help a lot for a starter, with "open_path(), open_serial()" :)
