### ISSUE TITLE
Wondering why the methods e.g. read()...

### ISSUE THREAD

**Issue by White-Rabbit-Scientific** [ruabmbua/hidapi-rs#143]
... are not listed on [https://docs.rs/hidapi/latest/hidapi/](https://docs.rs/hidapi/latest/hidapi/).

Ok, found them, well hidden, on here: https://docs.rs/hidapi/latest/hidapi/struct.HidDevice.html

Might be good for documentation to have the methods clearly listed. I had to click one a crate name, then a struct name to find them. #confusingForBeginners

**Comment by ruabmbua** [comment]
Added a note to the lib.rs documentation. There are already more examples in the examples/ directory.
