### ISSUE TITLE
Use Git version tags to publish releases on crates.io

### ISSUE THREAD

**Issue by uklotzde** [ruabmbua/hidapi-rs#147]
I have noticed that this repo is missing version tags.

With a secret API token from crates.io and a GitHub workflow this could be automated to prevent inconsistencies.

Example: https://github.com/slowtec/tokio-modbus/blob/main/.github/workflows/publish-release.yaml

**Comment by ruabmbua** [comment]
Will not do that (at least for now). I much prefer doing releases to crates.io by hand (or with the help of some scripts). I am manually testing on a few more platforms that are not available on github CI.

The inconsistent tag <-> crates.io release thing is mostly my fault. I always forget to push the tags.
