### ISSUE TITLE
[Question] why `gcc` as dependency?

### ISSUE THREAD

**Issue by Geobert** [ruabmbua/hidapi-rs#19]
Hi there,

I'm interested into this crate in order to interact with a custom HID device on Windows. I noticed the `gcc` dependency so my question is will this crate works with `msvc` target?

**Comment by Osspial** [comment]
`gcc` serves as an abstraction over all the platform-specific C compilers. So, on MSVC, it would call into the MSVC C compiler. It should work fine.
