### ISSUE TITLE
Transfer crate ownership

### ISSUE THREAD

**Issue by ruabmbua** [ruabmbua/hidapi-rs#23]
Hi @Osspial.

Could you transfer ownership, or add me as a owner of the hidapi crate like you suggested in #20 ?
I am currently cherry picking all from my perspective usable additions / fixes to the crate from various forks.

The source code is available at https://github.com/ruabmbua/hidapi-rs.

**Comment by Osspial** [comment]
I've invited you as an owner on crates.io and as a collaborator in this repository. It doesn't look like I can transfer ownership to you while you have a fork active, but if you delete the fork I should be able to do the transfer and then you can re-push your changes.

Sorry it took so long for this to happen!

**Comment by ruabmbua** [comment]
Thanks!

Dumb question: How do I view the crates.io invite? I did not get anything.

**Comment by ruabmbua** [comment]
Never mind, I found it.

**Comment by ruabmbua** [comment]
Can you try to transfer repo ownership again? I deleted my fork.

**Comment by Osspial** [comment]
The repo is under your username now, so it looks like it worked! Thanks for taking over.

**Comment by ruabmbua** [comment]
Ok it seems to work now :+1: .
