### ISSUE TITLE
Descriptors?

### ISSUE THREAD

**Issue by Geobert** [ruabmbua/hidapi-rs#31]
Hi,

First, thank you for this crate, it's really useful!

I was wondering if it's possible to get the Hid descriptors?

The device I work on report the maximum size accepted for a usb message in a "Hid descriptor" and I'd like to access it.

Regards

**Comment by ruabmbua** [comment]
Hi @Geobert ,

Hidapi does not implement report descriptor parsing, so it can't help you with getting the maximum size of a report.

You can however try to discovery the size with other measures, and then just assume a static size.

**Comment by Geobert** [comment]
I see, thank you for your answer. I'll need to rely on libusb as well then :)

**Comment by ruabmbua** [comment]
If your on linux, then do `cat /sys/kernel/debug/hid/0018\:06CB\:7A13.0001/rdesc`

**Comment by ruabmbua** [comment]
Or maybe use lsusb.

**Comment by Geobert** [comment]
Unfortunately, Windows here

**Comment by ruabmbua** [comment]
I think the device manager might even print the report of a device somehow. Check it out :smile:

**Comment by Geobert** [comment]
Maybe, but I need to adapt my packet size according to the device I'm talking to (similar devices, 2 different generations)

thank you anyway :D

**Comment by ruabmbua** [comment]
Oh okay. Maybe my rust library will support this in the future. I am currently spending some time on redoing everything in pure rust (and of course cross platform compatible). The goal is to have a rust library, which you can use to develop any kind of hid based userspace driver.

**Comment by jleni** [comment]
I know you asked about Windows, but maybe this helps.. 
I am also trying to get a descriptor in native Rust. Unfortunately something is not working. I can get the descriptor size but not the content.

https://stackoverflow.com/questions/51898034/how-to-use-ioctl-nix-macros-to-get-a-variable-size-buffer
