### ISSUE TITLE
HidError is a bit large

### ISSUE THREAD

**Issue by lnicola** [ruabmbua/hidapi-rs#45]
The 1.0 ship has sailed now (:tada:), but `HidError` is somewhat on the large side because of its `HidDeviceInfo` variant: 112 bytes on x64. Unfortunately, the compiler isn't too good at avoiding implicit copies (made for moves), so it's worth boxing it.

**Comment by ruabmbua** [comment]
Yea thats a good idea. I will try to make a fix.

**Comment by lnicola** [comment]
The problem is that the variant is public, so changing its type would technically be a breaking change. Maybe you can replace `HidDeviceInfo` with a boxed value, but..

**Comment by ruabmbua** [comment]
Resolved in https://github.com/ruabmbua/hidapi-rs/commit/c2a044d7ec2036b4b63b7997523ed2041ae7025e

**Comment by ruabmbua** [comment]
I just updated it to 1.0.1, I hope no one upgraded to 1.0.0 already.

Edit:
To be honest, I did not realize, that Rust implies that enum variant members are public. Makes sense because of the pattern matching... Never crossed my mind before.

**Comment by lnicola** [comment]
I upgraded, but don't worry :smile:. You can yank it, I suppose, but maybe nobody is looking at the fields in the error variants. It's very easy to break semver compat this way, though.

**Comment by ruabmbua** [comment]
I`ll yank 1.0.0 :P
