### ISSUE TITLE
Are there any ways to force-feedback gamepad?

### ISSUE THREAD

**Issue by TheRadioGuy** [ruabmbua/hidapi-rs#56]

**Comment by lnicola** [comment]
That might be possible, but you'd be served better by a crate like https://crates.io/crates/gilrs.

**Comment by TheRadioGuy** [comment]
`GilRS` supports only XInput gamepads

**Comment by ruabmbua** [comment]
In theory yes, as long as the gamepad is using hid to communicate with the host. There is no generic way to do it with all gamepads. You should try to use the OS API`s for gamepads.

Linux -> evdev, joydev
WIndows -> XInput, DirectInput

**Comment by TheRadioGuy** [comment]
Got it, thanks
