### ISSUE TITLE
Update to hidapi-0.10.1

### ISSUE THREAD

**Issue by haata** [ruabmbua/hidapi-rs#61]
hidapi-0.10.1 includes a number of fixes including Usage/Usage Page parsing in Linux (hidraw only so far; also works without udev rules or root permissions).

https://github.com/libusb/hidapi/releases/tag/hidapi-0.10.1

**Comment by ruabmbua** [comment]
Do you need any new things for the API, or is this just about the fixes?

**Comment by ruabmbua** [comment]
Updated hidapi submodule.

**Comment by haata** [comment]
I don't personally need anything out of the new API. The Usage/Usage Page fixes just make the already existing API work with hidraw.

**Comment by haata** [comment]
Thanks!
