### ISSUE TITLE
Relicense under MIT license

### ISSUE THREAD

**Issue by Osspial** [ruabmbua/hidapi-rs#8]
Currently, hidapi-rs is available under the LGPL license, which is unfortunately incompatible with the Apache license. Relicensing under the MIT license, using the BSD-style license from the upstream hidapi library, would allow such projects to use this crate. @ruabmbua consented in the original issue for this (#7), so right now this needs the consent of @newpavlov and @dyerti. If either of you don't give consent, please comment anyway so that your contributions may be rewritten.

Thanks!

**Comment by newpavlov** [comment]
I think it's a good idea and I am giving my consent.

**Comment by dyerti** [comment]
Cool with me. I consent.

**Comment by r8d8** [comment]
So, we good to go with a new licence?

**Comment by Osspial** [comment]
Yup! MIT has been pushed to crates.io.
