### ISSUE TITLE
Windows compilation error

### ISSUE THREAD

**Issue by YaroslavLisovets** [ruabmbua/hidapi-rs#82]
cargo:
[dependencies]
hidapi = "1.4.0"

code:
extern crate hidapi;
fn main() {
    hidapi::HidApi::new();
}

error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.12i46jyumlh4xedn.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.19uwt0zut2704p1g.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.23q9zvrdc2urzbj0.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.25v5qqadox4eyh1o.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.29uzaf8dip0jutf.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.2t6f9wwfysvr7tcp.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.2wau9md7y0obh1gj.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.4b7u0rep0o6xcjbj.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.4eqgjdqyhm1pli8d.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.id6st63hjy50aqs.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.jo8x4vl2gvkco8l.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.oonu0ycx83i40wd.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.xn92v2i10fmvdqv.rcgu.o" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.2u01zg3yniqjmvtg.rcgu.o" "/LIBPATH:C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps" "/LIBPATH:C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\build\\hidapi-024121b77bc94cdf\\out" "/LIBPATH:C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\libhidapi-1eb6b0f900106788.rlib" "C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\liblibc-185fe7e94c51aa2f.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-4751e4cf24f24492.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-448c9e26dc1e8b7f.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-b544eb318634c0c9.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-7178df6f94903ff9.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-3cff89399a08009d.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libminiz_oxide-f7ccafa8647fabd7.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libadler-c0eedc8ad62bebd1.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-3f2c861affd689b8.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-e32eef50c949be8c.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-28a478d347538790.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-4c39873e011bda7c.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-5271b3896c58e51b.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-665ed95809278e59.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-c2100e40c13f915d.rlib" "C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-3d43ec3df25f1c0b.rlib" "setupapi.lib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\Dev\\Hobby\\Rust\\test_hid_project\\target\\debug\\deps\\test_hid_project.exe" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\yrosl\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note:    Creating library C:\Dev\Hobby\Rust\test_hid_project\target\debug\deps\test_hid_project.lib and object C:\Dev\Hobby\Rust\test_hid_project\target\debug\deps\test_hid_project.exp
          libhidapi-1eb6b0f900106788.rlib(hidapi-1eb6b0f900106788.hidapi.08819f86-cgu.2.rcgu.o) : error LNK2019: unresolved external symbol libusb_set_option referenced in function _ZN6hidapi6HidApi21new_without_enumerate17h3fe8f24dfaa0ca6eE
          libhidapi-1eb6b0f900106788.rlib(hidapi-1eb6b0f900106788.hidapi.08819f86-cgu.2.rcgu.o) : error LNK2019: unresolved external symbol hid_libusb_wrap_sys_device referenced in function _ZN6hidapi6HidApi15wrap_sys_device17hbee55dd5d2b7269bE
          C:\Dev\Hobby\Rust\test_hid_project\target\debug\deps\test_hid_project.exe : fatal error LNK1120: 2 unresolved externals

**Comment by tfx2001** [comment]
Looks like it has been fixed in `1.4.1`

**Comment by YaroslavLisovets** [comment]
> Looks like it has been fixed in `1.4.1`
Yeah. It has fixed.

**Comment by cecton** [comment]
I got this error today. I think it would be best to yank the 1.4.0 so cargo will probably try to exclude it or at least warn if the user uses it.

**Comment by ruabmbua** [comment]
I need to invest some time in re-creating CI piplines for all those platforms. Unfortunately the CI we had some time ago is not available any more.
