### ISSUE TITLE
Crash rescanning for devices on macOS M1 

### ISSUE THREAD

**Issue by timfish** [ruabmbua/hidapi-rs#85]
I'm currently unsure if this is a Mac M1 issue with hidapi ([related issue here](https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/2431)) or just as likely it's caused by something unsupported I'm doing with threads. I'm currently calling `hidapi-rs` via `napi-rs` from node.js in Electron 😬. The first open always succeeds and subsequent calls crash the process.

Is there anything in particular that I should be carful about regarding which thread I should be calling `hidapi-rs` from?

![image](https://user-images.githubusercontent.com/1150298/175967881-2b38e588-979a-48ae-a20a-5b5d79bb75f0.png)

<img width="916" alt="image" src="https://user-images.githubusercontent.com/1150298/175963385-3cf7f0c3-8f49-40b5-8894-c47ee0641321.png">

**Comment by ruabmbua** [comment]
Are you maybe opening the same device multiple times? There is an issue in hidapi where opening the same device multiple times can result in a crash.

Regarding threads:

I can`t really give any guarantees about this, I do not know how the different backends in the C library act when called from different threads. Its better to run hidapi in one thread, and use e.g. message passing with channels to serve other threads.

Also, I just checked, and it seems HidApi is at least *Send*, I think I am going to fix that to make it not send-able to a different thread.

**Comment by timfish** [comment]
> Are you maybe opening the same device multiple times

For testing, the devices I'm using have no programmed serial number so I can only open with vid/pid. 

However, it crashes on the 2nd attempt to open a device, regardless of whether it found a device on the first search so I'm guessing it's not related to that issue.

>  Its better to run hidapi in one thread, and use e.g. message passing with channels to serve other threads

Thanks, that is what I'll try next and report back!

**Comment by timfish** [comment]
Confirmed that everything works without crashes if all calls to `hidapi` come from a single thread!
