### ISSUE TITLE
Having issues opening game controller with open_path

### ISSUE THREAD

**Issue by LuggaFiech** [ruabmbua/hidapi-rs#87]
I just can't get open_path to work. Below is my code. Please let me know what i'm doing wrong here.
![Screenshot 2022-07-21 203212](https://user-images.githubusercontent.com/74405184/180287758-132efc2b-5cc7-4fc6-9616-96ac33bcf473.jpg)
Error:
![image](https://user-images.githubusercontent.com/74405184/180288094-373257f0-4f0f-4fb4-9804-3e45164b54ce.png)

**Comment by ruabmbua** [comment]
I assume you are using windows (the path). Can you try opening it with vid + pid instead? I never tried to open by path on windows.

**Comment by LuggaFiech** [comment]
My problem is that i need to open only one page of the device. How would i do that only with vid and pid?

**Comment by ruabmbua** [comment]
Hm, it might not be possible then. You `ll have to check if the hidapi C library allows that on windows, we use it as the backend.

**Comment by LuggaFiech** [comment]
Ok thanks for the answer.

**Comment by ruabmbua** [comment]
You can try listing the devices with their usage pages with the library. If the multiple usage pages do not show up, it might be unimplemented for windows.

**Comment by LuggaFiech** [comment]
If i try it for every device it only prints one usage page each time so it might be unimplemented then.

**Comment by ruabmbua** [comment]
Only recently this started working on linux hidraw, so it might just be too new. Also, entirely possible that the windows API does not allow it?

**Comment by LuggaFiech** [comment]
I assume if you open a device with vid and pid it opens the standard usage page?

**Comment by ruabmbua** [comment]
Probably (it does for my devices), but entirely possible it just opens the one first in the descriptors (is that the default?).

**Comment by LuggaFiech** [comment]
Because i'm building the device myself i have the ability to manage the order of the usage pages so i will try to manage it like that. Thanks for helping.
