### ISSUE TITLE
Incorrect Function Error when using get_feature_report

### ISSUE THREAD

**Issue by Manul-Keyboard** [ruabmbua/hidapi-rs#88]
Code:
![image](https://user-images.githubusercontent.com/109975829/181344303-05abf35b-9192-4ba6-9bd2-6596bc358280.png)
Error:
![image](https://user-images.githubusercontent.com/109975829/181344383-e1b3b92a-80a4-4d2e-8549-d057cb056454.png)

**Comment by ruabmbua** [comment]
There is not any space in your buffer to actually write the received report into.
Use a larger buf.

Also as per documentation:

> Set the first byte of buf to the ‘Report ID’ of the report to be read. Upon return, the first byte will still contain the Report ID, and the report data will start in buf[1].

The first byte in the given buf is input, and contains the report id you wish to receive.

**Comment by Manul-Keyboard** [comment]
Thank you for your answer. It's working now.
