### ISSUE TITLE
write method not found

### ISSUE THREAD

**Issue by LuggaFiech** [ruabmbua/hidapi-rs#99]
Code snippet:
![image](https://user-images.githubusercontent.com/74405184/212173818-84ac459b-685b-428d-a71a-c26eeae1bc18.png)

The code snippet shown above returns the following error:
![image](https://user-images.githubusercontent.com/74405184/212173958-911ffde7-ffee-412a-88fa-725179084247.png)

**Comment by lnicola** [comment]
open returns a Result, you need to handle the potential error or call unwrap on it. I suggest giving the Rust book a read it you haven't already.
